---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webtools-pse-data
spec:
  selector:
    matchLabels:
      app: webtools-pse-data
  replicas: 1
  template:
    metadata:
      labels:
        app: webtools-pse-data
    spec:
      containers:
      - name: webtools-pse-data
        image: "ikoyski/webtools-pse-data:latest"
        imagePullPolicy: Always
        ports:
          - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: webtools-pse-data
spec:
  selector:
    app: webtools-pse-data
  ports:
  - protocol: "TCP"
    port: 8094
    targetPort: 8094
  type: NodePort
  